### ISSUE TITLE
Wrong Time Format?

### ISSUE THREAD

**Issue by jpalarchio** [dalinicus/homeassistant-aerogarden#28]
I'm fairly new to Home Assistant so if this is a misconfiguration on my part, I apologize.

The "Days Since Planting" and "Nutrient Days Left" both appear as hours on my dashboard.  What is odd to me is that if I click the entity, the history chart shows the days value and the options to change the display precision all represent days.

As an example, my dashboard shows "1584:00:00" but the history chart shows "66".

Is this a bug or a configuration issue by me?

![image](https://github.com/dalinicus/homeassistant-aerogarden/assets/5162617/5ea2f326-2d96-49d9-bd13-ccb3a6d85808)

**Comment by dalinicus** [comment]
Sorry, I initially missed this report, but I also noticed it this morning.  Seems something changed with homeassistant-core, and I suspect its a bug on their end.  I've switched to using `unit_of_measurement` instead of `native_unit_of_measurement` from within the data coordinator and it appears to solve the issue.  Should be fixed in 1.4.1

**Comment by dalinicus** [comment]
![image](https://github.com/dalinicus/homeassistant-aerogarden/assets/8620219/abc3ba86-565c-4d54-ad88-41c81e71fc7b)
Closing as fixed :) thanks for the report.

**Comment by jpalarchio** [comment]
Great, thanks!
